[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]


[rpc_endpoints]

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
